#!/usr/bin/env python3
# usage: $ oj generate-input 'python3 generate.py'
import random


# generated by online-judge-template-generator v4.7.1 (https://github.com/online-judge-tools/template-generator)
def main():
    n = random.randint(1, 1000)  # TODO: edit here
    a = [None for _ in range(n)]
    for i in range(n):
        a[i] = random.randint(1, 10**9)  # TODO: edit here
    print(n)
    for i in range(n):
        print(a[i])


if __name__ == "__main__":
    main()
