#!/usr/bin/env python3
# from typing import *


# def solve(n: int, a: List[int]) -> Tuple[List[str], List[List[str]]]:
def solve(n, a):
    pass  # TODO: edit here


# generated by online-judge-template-generator v4.7.1 (https://github.com/online-judge-tools/template-generator)
def main():
    n = int(input())
    a = [None for _ in range(n)]
    for i in range(n):
        a[i] = int(input())
    b, d = solve(n, a)
    for i in range(n):
        print(b[i])
        print(*[d[i][j] for j in range(b_i)])


if __name__ == '__main__':
    main()
